### ISSUE TITLE
Global search term disappears

### ISSUE THREAD

**Issue by DutchPete** [HarmfulBreeze/obsidian-material-3-theme#10]
Hello, 1st of all congratulations on a beautiful theme, well done 👍

When you do a global search, while typing out the search term the letters disappear to the left. In the screenshot below, the search term is "canada", but as you can see the term has disappeared - see red arrow.

![Image](https://github.com/user-attachments/assets/11654b44-69f9-4dfb-876d-e467d4afbe3f)

**Comment by HarmfulBreeze** [comment]
Hi, thank you for the kind words!

This is a search bar I missed because I was mainly focused on the ones in the settings, thanks for catching it.
This should be fixed with [v1.2.1](https://github.com/HarmfulBreeze/obsidian-material-3-theme/releases/tag/v1.2.1), please reopen this issue if needed :)

**Comment by DutchPete** [comment]
Updated the theme and it is fixed. Many thanks for your quick reaction.

**Comment by DutchPete** [comment]
I am on the latest version and the issue is back.

I accidentally opened another issue (#26), I will close it. My apologies.

**Comment by HarmfulBreeze** [comment]
Sorry about it, I'm not sure what caused it to be back.
I'll release a hotfix later today.

**Comment by HarmfulBreeze** [comment]
Should be fixed in 1.7.2 :)

**Comment by DutchPete** [comment]
It is, thank you.
